[package]
name = "git-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
ratatui = "0.29.0"
reqwest = { version="0.13.1", features=[ "json" ]}
serde = "1.0.228"
serde_json = "1.0.149"
tokio = "1.49.0"